# Generated by Django 5.0.3 on 2024-03-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(help_text="To'liq ism kiriting ", max_length=100),
        ),
    ]
