# Generated by Django 5.0.3 on 2024-03-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0002_alter_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
