# Generated by Django 5.0.3 on 2024-03-27 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitirganStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('end_of_date', models.DateField()),
                ('image', models.ImageField(upload_to='media')),
                ('ielts', models.CharField(choices=[('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9')], max_length=3)),
                ('insta_url', models.URLField()),
                ('face_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Bitiruvchi',
                'verbose_name_plural': 'Bitiruvchilar',
            },
        ),
        migrations.CreateModel(
            name='LevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('text', models.TextField(max_length=500)),
                ('level_name', models.CharField(choices=[('A1 - Beginner', 'A1 - Beginner'), ('A2 - Elementary', 'A2 - Elementary'), ('B1 - Pre Intermediate', 'B1 - Pre Intermediate'), ('B1+ - Intermediate', 'B1+ - Intermediate'), ('B2 - Upper Intermediate', 'B2 - Advanced'), ('IELTS', 'IELTS')], max_length=35)),
                ('price_level', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='task_for_stuent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
