# Generated by Django 5.0.3 on 2024-03-24 00:47

import learning_center.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100, validators=[learning_center.validators.address])),
                ('location_phone_number', models.CharField(max_length=100, validators=[learning_center.validators.validate_phone_number])),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='LevelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('text', models.TextField(max_length=500)),
                ('level_name', models.CharField(choices=[('A1 - Beginner', 'A1 - Beginner'), ('A2 - Elementary', 'A2 - Elementary'), ('B1 - Pre Intermediate', 'B1 - Pre Intermediate'), ('B1+ - Intermediate', 'B1+ - Intermediate'), ('B2 - Upper Intermediate', 'B2 - Advanced'), ('IELTS', 'IELTS')], max_length=35)),
                ('price_level', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='task_for_stuent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
