# Generated by Django 5.0.3 on 2024-03-24 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task_for_stuent',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_center.levelmodel'),
        ),
        migrations.AddField(
            model_name='task_for_stuent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_center.studentmodel'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task_for_stuent',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning_center.teachermodel'),
        ),
    ]
