# Generated by Django 5.0.3 on 2024-03-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AlterField(
            model_name='levelmodel',
            name='text',
            field=models.TextField(help_text='Text Kiriting', max_length=500),
        ),
        migrations.AlterField(
            model_name='task_for_stuent',
            name='description',
            field=models.TextField(help_text="O'quvchi nima qilishi kerakligini yozing", max_length=500),
        ),
    ]
