# Generated by Django 5.0.3 on 2024-03-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelmodel',
            name='file',
            field=models.FileField(default=0, upload_to='files/'),
            preserve_default=False,
        ),
    ]
