# Generated by Django 5.0.3 on 2024-03-24 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0003_delete_address_alter_levelmodel_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_for_stuent',
            name='video',
            field=models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
