# Generated by Django 5.0.3 on 2024-03-27 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0003_levelmodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelmodel',
            name='file',
        ),
    ]
