# Generated by Django 5.0.3 on 2024-03-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0004_alter_task_for_stuent_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelmodel',
            name='text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='task_for_stuent',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
