# Generated by Django 5.0.3 on 2024-03-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0005_alter_levelmodel_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitirganStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('end_of_date', models.DateField()),
                ('ielts', models.CharField(choices=[('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9')], max_length=3)),
            ],
            options={
                'verbose_name': 'Bitiruvchi',
                'verbose_name_plural': 'Bitiruvchilar',
            },
        ),
        migrations.AlterModelOptions(
            name='task_for_stuent',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
