# Generated by Django 5.0.3 on 2024-03-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0006_bitirganstudent_alter_task_for_stuent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitirganstudent',
            name='image',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
    ]
