# Generated by Django 5.0.3 on 2024-03-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_center', '0007_bitirganstudent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitirganstudent',
            name='face_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bitirganstudent',
            name='insta_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
